version: '3.8'
services:
  db:
    image: mysql:5.7.30
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=gdl_desenv
      - MYSQL_ROOT_PASSWORD=100grilo
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local